"""Scaffold a ``cq.toml`` for a repository that does not have one yet.

``cq`` has no implicit default roots: without ``cq.toml`` every command fails
closed.  That is the correct behaviour for correctness, but it makes the first
five minutes in a new repository unnecessarily hard.  This script inspects the
working tree and proposes the roots that actually contain indexable source.

The extension allowlist is **not** re-declared here; it is imported from
``cq.languages`` so that the proposal can never drift from what the indexer
would really accept.

Usage::

    python init_config.py --repo-root . --profile main
    python init_config.py --repo-root . --profile main --force
    python init_config.py --repo-root . --dry-run
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path, PurePosixPath
from typing import Iterable, Sequence

_VENDOR = Path(__file__).resolve().parent / "vendor"
if _VENDOR.is_dir():
    sys.path.insert(0, str(_VENDOR))

try:
    from cq import discovery
    from cq.config import DEFAULT_MAX_FILE_BYTES
    from cq.languages import LANGUAGE_BY_SUFFIX
except ImportError as exc:  # pragma: no cover - surfaced to the operator
    raise SystemExit(
        f"cannot import the cq engine ({exc}). The kit was copied without its "
        "engine; re-copy the whole directory, or put the cq package on PYTHONPATH."
    ) from exc

# 索引時の組み込み除外とは別に、ルート候補の提案から外すディレクトリ。
# 依存物・生成物をルートに提案すると、利用者が最初に見る cq.toml が誤りになる。
NOISY_TOP_LEVEL = frozenset({
    ".git", ".github", ".venv", "venv", "node_modules", "vendor", "third_party",
    "dist", "build", "out", "bin", "obj", "target", "coverage", "__pycache__",
    ".mdq", ".cq", ".idea", ".vscode",
})

TEMPLATE = """# cq configuration ({profile} profile).
#
# Generated by the code-query kit (init_config.py).
# Schema reference: vendor/cq/config.py inside the kit.

[index]
# Files larger than this are treated as build output and skipped.
max_file_bytes = {max_file_bytes}

[profiles.{profile}]
roots = [{roots}]
{exclude}"""

# Dependency trees that git lists as untracked whenever the target repository has
# no ignore rule for them. A kit venv alone adds thousands of site-packages files.
GENERATED_EXCLUDES = ("**/.venv*/**", "**/node_modules/**")


class InitError(RuntimeError):
    """Raised when a configuration cannot be proposed safely."""


def indexable_suffixes() -> frozenset[str]:
    return frozenset(LANGUAGE_BY_SUFFIX)


def count_by_top_level(
    paths: Iterable[str], *, skip_prefixes: Sequence[str] = ()
) -> Counter[str]:
    """Count indexable files per first path segment.

    Repository-root files are ignored on purpose: ``cq`` roots must be
    directories (``cq.config._normalise_root`` rejects ``.``), so a file that
    lives directly at the root cannot be covered by any profile.

    ``skip_prefixes`` drops the distribution kits, so that copying a kit into the
    target repository does not make its scripts look like the code the user wants
    to search. Virtualenv trees are dropped for the same reason.
    """
    suffixes = indexable_suffixes()
    counts: Counter[str] = Counter()
    for rel in paths:
        if any(rel == prefix or rel.startswith(prefix + "/") for prefix in skip_prefixes):
            continue
        pure = PurePosixPath(rel)
        if any(part.startswith(".venv") for part in pure.parts[:-1]):
            continue
        if len(pure.parts) < 2:
            continue
        top = pure.parts[0]
        if top in NOISY_TOP_LEVEL:
            continue
        if pure.suffix.lower() in suffixes:
            counts[top] += 1
    return counts


def self_prefix(repo_root: Path) -> str | None:
    """Return this kit's location relative to ``repo_root``, when inside it."""
    try:
        return Path(__file__).resolve().parent.relative_to(repo_root).as_posix()
    except ValueError:
        return None


def kit_prefixes(repo_root: Path) -> list[str]:
    """Locations of every distribution kit sitting next to this one.

    Kits are usually copied side by side (``tools/kits/markdown-query`` and
    ``tools/kits/code-query``), and none of them is code the user wants indexed.
    """
    own = self_prefix(repo_root)
    if own is None:
        return []
    prefixes = {own}
    for manifest in Path(__file__).resolve().parents[1].glob("*/kit.toml"):
        try:
            prefixes.add(manifest.parent.relative_to(repo_root).as_posix())
        except ValueError:
            continue
    return sorted(prefixes)


def render(profile: str, roots: Sequence[str], exclude: Sequence[str]) -> str:
    rendered_roots = ", ".join(f'"{r}"' for r in roots)
    if exclude:
        lines = "\n".join(f'    "{e}",' for e in exclude)
        rendered_exclude = f"exclude = [\n{lines}\n]\n"
    else:
        rendered_exclude = ""
    return TEMPLATE.format(
        profile=profile,
        max_file_bytes=DEFAULT_MAX_FILE_BYTES,
        roots=rendered_roots,
        exclude=rendered_exclude,
    )


def build(
    repo_root: Path,
    profile: str,
    *,
    min_files: int,
    exclude: Sequence[str],
    lister=discovery.git_lister,
) -> tuple[str, Counter[str], list[str]]:
    listed = lister(repo_root)
    kits = kit_prefixes(repo_root)
    counts = count_by_top_level(listed, skip_prefixes=kits)
    roots = [name for name, n in sorted(counts.items()) if n >= min_files]
    if not roots:
        raise InitError(
            "no directory under this repository contains indexable source files "
            f"({', '.join(sorted(indexable_suffixes()))}). "
            "cq indexes source code only; use markdown-query for .md and CSV/TSV."
        )
    excludes = [f"{prefix}/**" for prefix in kits if prefix.split("/")[0] in roots]
    excludes += list(exclude)
    excludes += list(GENERATED_EXCLUDES)
    return render(profile, roots, excludes), counts, roots


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="init_config.py")
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--profile", default="main")
    parser.add_argument("--output", default=None, help="default: <repo-root>/cq.toml")
    parser.add_argument("--min-files", type=int, default=1,
                        help="minimum indexable files for a directory to become a root")
    parser.add_argument("--exclude", action="append", default=[],
                        help="extra exclude glob (repeatable)")
    parser.add_argument("--force", action="store_true", help="overwrite an existing file")
    parser.add_argument("--dry-run", action="store_true", help="print without writing")
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    if not repo_root.is_dir():
        print(f"error: repo root does not exist: {repo_root}", file=sys.stderr)
        return 2

    target = Path(args.output) if args.output else repo_root / "cq.toml"
    if target.exists() and not (args.force or args.dry_run):
        print(f"error: {target} already exists; pass --force to overwrite", file=sys.stderr)
        return 2

    try:
        text, counts, roots = build(
            repo_root, args.profile, min_files=args.min_files, exclude=args.exclude
        )
    except (InitError, discovery.DiscoveryError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    for name in sorted(counts):
        marker = "+" if name in roots else " "
        print(f"  {marker} {name}/  {counts[name]} indexable file(s)", file=sys.stderr)

    if args.dry_run:
        sys.stdout.write(text)
        return 0

    target.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {target}", file=sys.stderr)
    print(f"next: index with --profile {args.profile}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
