"""Scaffold an ``mdq.toml`` for a repository that does not have one yet.

Without a config file ``mdq`` falls back to ``GENERIC_DEFAULT_ROOTS``
(``docs`` / ``users-guide``). That is a safe default but it silently skips
every other documentation root, so the first index in a new repository is
often almost empty. This script proposes the roots that actually contain
Markdown.

The file walker is **not** re-implemented here; ``mdq.indexer.iter_markdown``
is used so the proposal can never drift from what the indexer really accepts.

Usage::

    python init_config.py --repo-root . --dry-run
    python init_config.py --repo-root .
    python init_config.py --repo-root . --force
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path, PurePosixPath
from typing import Sequence

_VENDOR = Path(__file__).resolve().parent / "vendor"
if _VENDOR.is_dir():
    sys.path.insert(0, str(_VENDOR))

try:
    from mdq.config import CONFIG_FILENAMES, GENERIC_DEFAULT_ROOTS
    from mdq.indexer import iter_markdown
except ImportError as exc:  # pragma: no cover - surfaced to the operator
    raise SystemExit(
        f"cannot import the mdq engine ({exc}). The kit was copied without its "
        "engine; re-copy the whole directory, or put the mdq package on PYTHONPATH."
    ) from exc

# Directories that hold dependencies or build output. Proposing them as roots
# would make the first mdq.toml a user sees wrong.
NOISY_TOP_LEVEL = frozenset({
    ".git", ".github", ".venv", "venv", "node_modules", "vendor", "third_party",
    "dist", "build", "out", "bin", "obj", "target", "coverage", "__pycache__",
    ".mdq", ".cq", ".idea", ".vscode",
})

TEMPLATE = """# mdq configuration for this repository.
#
# Generated by the markdown-query kit (init_config.py).
# Schema reference: vendor/mdq/config.py inside the kit.

[index]
roots = [
{roots}
]
{exclude}"""


def kit_prefixes(repo_root: Path) -> list[str]:
    """Locations of every distribution kit sitting inside ``repo_root``.

    Kits carry their own documentation, and a kit venv carries whatever Markdown
    its dependencies ship. Neither is content the user wants to search.
    """
    prefixes: list[str] = []
    for manifest in sorted(Path(__file__).resolve().parents[1].glob("*/kit.toml")):
        try:
            prefixes.append(manifest.parent.relative_to(repo_root).as_posix())
        except ValueError:
            continue
    return prefixes


def is_noise(rel: str, prefixes: Sequence[str]) -> bool:
    if any(rel == prefix or rel.startswith(prefix + "/") for prefix in prefixes):
        return True
    return any(part.startswith(".venv") for part in PurePosixPath(rel).parts[:-1])


def propose_roots(repo_root: Path) -> list[tuple[str, int]]:
    """Return ``(root, markdown_file_count)`` for every promising top-level dir."""
    prefixes = kit_prefixes(repo_root)
    proposals: list[tuple[str, int]] = []
    for entry in sorted(repo_root.iterdir()):
        if not entry.is_dir() or entry.name in NOISY_TOP_LEVEL:
            continue
        count = 0
        for path in iter_markdown(repo_root, [entry.name]):
            try:
                rel = path.relative_to(repo_root).as_posix()
            except ValueError:
                rel = path.as_posix()
            if not is_noise(rel, prefixes):
                count += 1
        if count:
            proposals.append((entry.name, count))
    return proposals


def render(roots: Sequence[str], excludes: Sequence[str] = ()) -> str:
    body = "\n".join(f'    "{root}",' for root in roots)
    if excludes:
        lines = "\n".join(f'    "{pattern}",' for pattern in excludes)
        rendered_exclude = f"exclude = [\n{lines}\n]\n"
    else:
        rendered_exclude = ""
    return TEMPLATE.format(roots=body, exclude=rendered_exclude)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing mdq.toml.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print the proposal without writing it.")
    args = parser.parse_args(argv)

    repo_root = args.repo_root.resolve()
    if not repo_root.is_dir():
        print(f"[markdown-query init] not a directory: {repo_root}", file=sys.stderr)
        return 2

    existing = [repo_root / name for name in CONFIG_FILENAMES]
    present = [p for p in existing if p.is_file()]
    target = repo_root / CONFIG_FILENAMES[0]
    if present and not args.force and not args.dry_run:
        print(f"[markdown-query init] {present[0]} already exists; keeping it "
              "(use --force to regenerate).")
        return 0

    proposals = propose_roots(repo_root)
    roots = [name for name, _ in proposals] or list(GENERIC_DEFAULT_ROOTS)
    # A kit under a proposed root still has to be excluded: the proposal only
    # decides which directories are walked, not what the walk yields.
    excludes = [
        f"{prefix}/**"
        for prefix in kit_prefixes(repo_root)
        if prefix.split("/")[0] in roots
    ]
    content = render(roots, excludes)

    for name, count in proposals:
        print(f"[markdown-query init] {name}/: {count} markdown file(s)")
    if not proposals:
        print("[markdown-query init] no markdown found; falling back to "
              f"{GENERIC_DEFAULT_ROOTS}")

    if args.dry_run:
        print(content)
        return 0

    target.write_text(content, encoding="utf-8", newline="\n")
    print(f"[markdown-query init] wrote {target}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
